
services:
  mongodb:
    image: mongo:5.0
    container_name: ecommerce-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo_data:/data/db

  nats:
    image: nats:2.9
    container_name: ecommerce-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--http_port 8222"

